# Set true color
# set-option -sa terminal-overrides ",xterm*:Tc"
set -g extended-keys-format csi-u

# bad !!
set -g mouse on

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

# Set prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Clipboard
set -g set-clipboard on

# CTRL Backspace
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Window navigation
bind -n M-H previous-window
bind -n M-Q previous-window
bind -n M-L next-window
bind -n M-E next-window

# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key h split-window -v
bind-key v split-window -h

# Opens panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Tmux layout
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
